# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# NeoForge
neo_version=21.1.209
neo_version_range=[21.1.0,)
loader_version_range=[1,)

# Dependencies
jei_version=19.25.0.322
appleskin_version=mc1.21-3.0.7

# Mod properties
mod_id=floraexpansion
mod_name=Flora Expansion
mod_license=MIT License
mod_version=0.4.1r
mod_group_id=de.artemis.floraexpansion
mod_authors=DoomedArtemis
mod_description=Adds new natural details to Minecraft's worlds. Expands the variety of plants and improves the look and feel of its flora and foliage.
