# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20

# Minecraft
minecraft_version=1.21.11
minecraft_version_range=[1.21.11]

# NeoForge
neo_version=21.11.42
neo_version_range=[21.11.42,)
loader_version_range=[1,)

# Dependencies
jei_version=27.4.0.17
appleskin_version=mc1.21.11-3.0.8

# Mod properties
mod_id=floraexpansion
mod_name=Flora Expansion
mod_license=MIT License
mod_version=0.4.1r
mod_group_id=de.artemis.floraexpansion
mod_authors=DoomedArtemis
mod_description=Adds new natural details to Minecraft's worlds. Expands the variety of plants and improves the look and feel of its flora and foliage.
