package de.artemis.floraexpansion.common.datagen;

import de.artemis.floraexpansion.FloraExpansion;
import de.artemis.floraexpansion.common.registry.ModBlocks;
import de.artemis.floraexpansion.common.registry.ModItems;
import net.minecraft.data.PackOutput;

@SuppressWarnings("unused")
public class ModLanguageProvider extends net.neoforged.neoforge.common.data.LanguageProvider {
    public ModLanguageProvider(PackOutput output, String locale) {
        super(output, FloraExpansion.MODID, locale);
    }

    @Override
    protected void addTranslations() {
        add("floraexpansion.creative_tab", "Flora Expansion");
        add("tooltip.floraexpansion.crate_contents_suffix", " stored");

        add("jei.floraexpansion.basket.info.1", "Right-click mature crops and berry-like plants with a basket to collect their harvest without uprooting them.");
        add("jei.floraexpansion.basket.info.2", "Crop-style plants are replanted automatically, including vanilla and many modded crops that use normal crop behavior.");
        add("jei.floraexpansion.basket.info.3", "Right-click in the air, or Shift-right-click a block, to open the basket's 9 inventory slots.");
        add("jei.floraexpansion.pine_litter.info.1", "Right-click with an empty main hand to gather pine cones and twigs from pine litter.");
        add("jei.floraexpansion.pine_litter.info.2", "Thicker patches can yield more pine cones and more twigs.");
        add("jei.floraexpansion.pine_litter.info.3", "Bonemeal increases the patch up to 4 layers instead of spreading to a new block.");
        add("jei.floraexpansion.pine_litter.info.4", "Using bonemeal on a full 4-layer patch drops another pine litter block.");
        add("jei.floraexpansion.pine_cone.info.1", "Pine cones can be thrown.");
        add("jei.floraexpansion.pine_cone.info.2", "Thrown pine cones deal a small amount of damage and briefly slow targets.");
        add("jei.floraexpansion.pine_cone.info.3", "On impact, they sometimes drop 1 or 2 pine nuts.");
        add("jei.floraexpansion.pine_cone.info.4", "Burning pine cones can drop toasted pine nuts instead.");
        add("jei.floraexpansion.flax_seed.info.1", "Flax grows into a two-block crop once it reaches its taller stage.");
        add("jei.floraexpansion.flax_seed.info.2", "Right-click the upper half with shears to harvest the crop without replanting.");
        add("jei.floraexpansion.flax_seed.info.3", "Shearing resets flax back to a small lower-half plant so it can regrow faster.");
        add("jei.floraexpansion.flax_seed.info.4", "Bonemeal can advance flax growth and helps it reach the harvestable tall stage sooner.");
        add("jei.floraexpansion.pebble_patch.info.1", "Place more pebble patches onto the same block to build up the patch.");
        add("jei.floraexpansion.pebble_patch.info.2", "Right-click with an empty main hand to pick the pebbles back up.");
        add("jei.floraexpansion.pebble_patch.info.3", "A fuller patch returns more pebbles.");
        add("jei.floraexpansion.pebbles.info.1", "Pebbles can be thrown.");
        add("jei.floraexpansion.pebbles.info.2", "Thrown pebbles deal damage and usually drop themselves again on impact.");
        add("jei.floraexpansion.crate.info.1", "Crates hold only one kind of item at a time, but store far more of it than a barrel.");
        add("jei.floraexpansion.crate.info.2", "Right-click inserts the held stack, and quickly right-clicking twice deposits matching items from your inventory.");
        add("jei.floraexpansion.crate.info.3", "Left-click removes one item, while Shift-left-click removes a full stack.");
        add("jei.floraexpansion.crate.info.4", "Shift-right-click opens the full storage screen, and a redstone signal locks all hand, hopper, and menu access.");
        add("jei.floraexpansion.crate.info.5", "Use linen thread to tie a crate shut so it can be broken, moved with its contents, and opened again after placement.");
        add("jei.floraexpansion.linen_thread.info.1", "Linen thread can be used on a crate to tie it shut and preserve its contents when broken.");
        add("jei.floraexpansion.linen_thread.info.2", "Place the tied crate again and right-click it to untie the thread and restore normal access.");
        add("jei.floraexpansion.fruiting_cherry_leaves.info.1", "Fruiting cherry leaves slowly ripen over time.");
        add("jei.floraexpansion.fruiting_cherry_leaves.info.2", "Right-click by hand to harvest cherries once fruit has grown.");
        add("jei.floraexpansion.fruiting_cherry_leaves.info.3", "Riper leaves yield more cherries.");
        add("jei.floraexpansion.fruiting_cherry_leaves.info.4", "Bonemeal advances the fruiting stage.");
        add("jei.floraexpansion.cherries.info.1", "Eating cherries has a 50% chance to leave behind a cherry pit.");
        add("jei.floraexpansion.cherries.info.2", "Cherry pits can be planted to grow cherry trees.");
        add("jei.floraexpansion.cherry_pit.info.1", "Cherry pits are planted like saplings.");
        add("jei.floraexpansion.cherry_pit.info.2", "They can also come from eating cherries.");
        add("jei.floraexpansion.bottled_juice.info.1", "Drinking this returns an empty glass bottle.");
        add("jei.floraexpansion.bottled_juice.info.2", "The bottle is given back to the inventory or dropped nearby if there is no space.");
        add("jei.floraexpansion.fruiting_oak_leaves.info.1", "Fruiting oak leaves slowly ripen apples over time.");
        add("jei.floraexpansion.fruiting_oak_leaves.info.2", "Right-click by hand to harvest an apple once the leaves are fully ripe.");
        add("jei.floraexpansion.fruiting_oak_leaves.info.3", "Bonemeal advances the fruiting stage.");
        add("jei.floraexpansion.apple_core.info.1", "Apple cores are planted like saplings.");
        add("jei.floraexpansion.apple_core.info.2", "Eating apples has a 50% chance to leave behind an apple core.");
        add("jei.floraexpansion.giant_cactus_base.info.1", "Use an axe to strip giant cactus base blocks.");
        add("jei.floraexpansion.giant_cactus_base.info.2", "Stripping can knock loose a cactus thorn.");
        add("jei.floraexpansion.giant_cactus_wood.info.1", "Use an axe to strip giant cactus wood blocks.");
        add("jei.floraexpansion.giant_cactus_wood.info.2", "Stripping can knock loose a cactus thorn.");
        add("jei.floraexpansion.giant_cactus_stem.info.1", "Touching giant cactus stems deals cactus damage.");
        add("jei.floraexpansion.giant_cactus_stem.info.2", "Use an axe on the stem to harvest the whole connected stem column into cactus slices.");
        add("jei.floraexpansion.giant_cactus_stem.info.3", "Stems can keep growing upward and may produce cactus flowers at the top.");
        add("jei.floraexpansion.cactus_thorn.info.1", "Cactus thorns damage living entities that pass through them.");
        add("jei.floraexpansion.cactus_thorn.info.2", "They can be attached to floors, walls, or ceilings if the supporting block is sturdy enough.");
        add("jei.floraexpansion.giant_cactus_blossom.info.1", "Giant cactus blossoms can grow into giant cacti on sand or suitable terracotta.");
        add("jei.floraexpansion.giant_cactus_blossom.info.2", "They can transform on their own over time.");
        add("jei.floraexpansion.giant_cactus_blossom.info.3", "Bonemeal can also trigger giant cactus growth when there is enough room.");
        add("jei.floraexpansion.cactus_armor.info.1", "Cactus armor can retaliate against direct melee attackers.");
        add("jei.floraexpansion.cactus_armor.info.2", "Wearing more pieces increases the chance, and 3 or more pieces hit harder.");
        add("jei.floraexpansion.cactus_armor.info.3", "Fire Aspect on cactus armor can ignite attackers, but Thorns cannot be applied.");
        add("jei.floraexpansion.cactus_cluster.info.1", "Place more cactus clusters onto the same block to build up the cluster.");
        add("jei.floraexpansion.cactus_cluster.info.2", "Use a glass bottle to extract cactus juice.");
        add("jei.floraexpansion.cactus_cluster.info.3", "Each bottle use reduces the cluster by one stage.");
        add("jei.floraexpansion.opuntia_cactus.info.1", "Opuntia cacti slowly ripen prickly pears over time.");
        add("jei.floraexpansion.opuntia_cactus.info.2", "Right-click to harvest ripe fruit without breaking the plant.");
        add("jei.floraexpansion.opuntia_cactus.info.3", "Bonemeal ripens the plant immediately.");
        add("jei.floraexpansion.prickly_pear.info.1", "Prickly pears are the fruit harvested from opuntia cacti.");
        add("jei.floraexpansion.prickly_pear.info.2", "The item can also be planted to place a new opuntia cactus.");
        add("jei.floraexpansion.small_blueberry_bush.info.1", "Small blueberry bushes grow through three leafy stages before producing berries.");
        add("jei.floraexpansion.small_blueberry_bush.info.2", "Right-click a ripe bush to harvest blueberries without uprooting it.");
        add("jei.floraexpansion.small_blueberry_bush.info.3", "Harvesting resets the bush to its last leafy stage so it can fruit again sooner.");
        add("jei.floraexpansion.small_blueberry_bush.info.4", "Small blueberry bushes continue growing on their own over time.");
        add("jei.floraexpansion.large_blueberry_bush.info.1", "Large blueberry bushes grow through two leafy stages before they start fruiting.");
        add("jei.floraexpansion.large_blueberry_bush.info.2", "They can be harvested at the first berry stage, then harvested again for double yield when fully ripe.");
        add("jei.floraexpansion.large_blueberry_bush.info.3", "Harvesting by hand resets the bush to its later leafy stage, and shears pick the whole bush back up.");
        add("jei.floraexpansion.blueberry_pie.info.1", "Blueberry pie is eaten as a single food item, like pumpkin pie.");
        add("jei.floraexpansion.blueberry_pie.info.2", "It takes four times as long to eat as a blueberry pie slice.");
        add("jei.floraexpansion.blueberry_pie.info.3", "Eating it grants 5 seconds of regeneration, and it can also be crafted into 4 slices.");
        add("jei.floraexpansion.empty_jar.info.1", "Empty jars are used to preserve foods like blueberry jam.");
        add("jei.floraexpansion.empty_jar.info.2", "Eating jam returns the empty jar to your inventory or drops it nearby if there is no space.");
        add("jei.floraexpansion.blueberry_jam.info.1", "Blueberry jam is a preserved berry food made from blueberries, sugar, and an empty jar.");
        add("jei.floraexpansion.blueberry_jam.info.2", "Eating it returns the empty jar to your inventory or drops it nearby if there is no space.");
        add("jei.floraexpansion.strawberry.info.1", "Strawberries are planted directly, like carrots or potatoes.");
        add("jei.floraexpansion.strawberry.info.2", "Only fully grown strawberry plants drop strawberries when broken.");
        add("jei.floraexpansion.strawberry_jam.info.1", "Strawberry jam is a preserved berry food made from strawberries, sugar, and an empty jar.");
        add("jei.floraexpansion.strawberry_jam.info.2", "Eating it returns the empty jar to your inventory or drops it nearby if there is no space.");
        add("jei.floraexpansion.wooden_bucket.info.1", "Wooden buckets behave like normal buckets for water, powder snow, milk, and bucketable water creatures.");
        add("jei.floraexpansion.wooden_bucket.info.2", "Each successful use damages the bucket, and it breaks after 10 uses.");
        add("jei.floraexpansion.wooden_bucket.info.3", "They can scoop lava, but the wooden lava bucket chars into charcoal after a few seconds and sets its carrier on fire.");

        add(ModBlocks.PINE_LITTER.get(), "Pine Litter");
        add(ModBlocks.TWIG_LADDER.get(), "Twig Ladder");
        add(ModBlocks.CRATE.get(), "Crate");
        add(ModBlocks.BLUEBERRY_BUSH.get(), "Small Blueberry Bush");
        add(ModBlocks.LARGE_BLUEBERRY_BUSH.get(), "Large Blueberry Bush");
        add(ModBlocks.STRAWBERRY_PLANT.get(), "Strawberry Plant");
        add(ModBlocks.STRAWBERRY_CAKE.get(), "Strawberry Cake");
        add(ModBlocks.STRAWBERRY_CANDLE_CAKE.get(), "Strawberry Candle Cake");
        add(ModBlocks.WHITE_STRAWBERRY_CANDLE_CAKE.get(), "White Strawberry Candle Cake");
        add(ModBlocks.ORANGE_STRAWBERRY_CANDLE_CAKE.get(), "Orange Strawberry Candle Cake");
        add(ModBlocks.MAGENTA_STRAWBERRY_CANDLE_CAKE.get(), "Magenta Strawberry Candle Cake");
        add(ModBlocks.LIGHT_BLUE_STRAWBERRY_CANDLE_CAKE.get(), "Light Blue Strawberry Candle Cake");
        add(ModBlocks.YELLOW_STRAWBERRY_CANDLE_CAKE.get(), "Yellow Strawberry Candle Cake");
        add(ModBlocks.LIME_STRAWBERRY_CANDLE_CAKE.get(), "Lime Strawberry Candle Cake");
        add(ModBlocks.PINK_STRAWBERRY_CANDLE_CAKE.get(), "Pink Strawberry Candle Cake");
        add(ModBlocks.GRAY_STRAWBERRY_CANDLE_CAKE.get(), "Gray Strawberry Candle Cake");
        add(ModBlocks.LIGHT_GRAY_STRAWBERRY_CANDLE_CAKE.get(), "Light Gray Strawberry Candle Cake");
        add(ModBlocks.CYAN_STRAWBERRY_CANDLE_CAKE.get(), "Cyan Strawberry Candle Cake");
        add(ModBlocks.PURPLE_STRAWBERRY_CANDLE_CAKE.get(), "Purple Strawberry Candle Cake");
        add(ModBlocks.BLUE_STRAWBERRY_CANDLE_CAKE.get(), "Blue Strawberry Candle Cake");
        add(ModBlocks.BROWN_STRAWBERRY_CANDLE_CAKE.get(), "Brown Strawberry Candle Cake");
        add(ModBlocks.GREEN_STRAWBERRY_CANDLE_CAKE.get(), "Green Strawberry Candle Cake");
        add(ModBlocks.RED_STRAWBERRY_CANDLE_CAKE.get(), "Red Strawberry Candle Cake");
        add(ModBlocks.BLACK_STRAWBERRY_CANDLE_CAKE.get(), "Black Strawberry Candle Cake");
        add(ModBlocks.FLAX_CROP.get(), "Flax Crop");
        add(ModBlocks.LINEN_CARPET.get(), "Linen Carpet");
        add(ModBlocks.PEBBLE_PATCH.get(), "Pebble Patch");
        add(ModBlocks.PEBBLE_BLOCK.get(), "Pebble Block");
        add(ModBlocks.LINEN_BLOCK.get(), "Linen Block");
        add(ModBlocks.FLAX_BALE.get(), "Flax Bale");
        add(ModBlocks.CHERRY_PIT.get(), "Cherry Pit");
        add(ModBlocks.FRUITING_CHERRY_LEAVES.get(), "Fruiting Cherry Leaves");
        add(ModBlocks.POTTED_CHERRY_PIT.get(), "Potted Cherry Pit");
        add(ModBlocks.APPLE_CORE.get(), "Apple Core");
        add(ModBlocks.POTTED_APPLE_CORE.get(), "Potted Apple Core");
        add(ModBlocks.FRUITING_OAK_LEAVES.get(), "Fruiting Oak Leaves");
        add(ModBlocks.GIANT_CACTUS_BASE.get(), "Giant Cactus Base");
        add(ModBlocks.STRIPPED_GIANT_CACTUS_BASE.get(), "Stripped Giant Cactus Base");
        add(ModBlocks.GIANT_CACTUS_STEM.get(), "Giant Cactus Stem");
        add(ModBlocks.POTTED_GIANT_CACTUS_STEM.get(), "Potted Giant Cactus Stem");
        add(ModBlocks.CACTUS_THORN.get(), "Cactus Thorn");
        add(ModBlocks.GIANT_CACTUS_BLOSSOM.get(), "Giant Cactus Blossom");
        add(ModBlocks.GIANT_CACTUS_WOOD.get(), "Giant Cactus Wood");
        add(ModBlocks.STRIPPED_GIANT_CACTUS_WOOD.get(), "Stripped Giant Cactus Wood");
        add(ModBlocks.CACTUS_PLANKS.get(), "Cactus Planks");
        add(ModBlocks.CACTUS_MOSAIC.get(), "Cactus Mosaic");
        add(ModBlocks.CACTUS_STAIRS.get(), "Cactus Stairs");
        add(ModBlocks.CACTUS_SLAB.get(), "Cactus Slab");
        add(ModBlocks.CACTUS_FENCE.get(), "Cactus Fence");
        add(ModBlocks.CACTUS_FENCE_GATE.get(), "Cactus Fence Gate");
        add(ModBlocks.CACTUS_BUTTON.get(), "Cactus Button");
        add(ModBlocks.CACTUS_PRESSURE_PLATE.get(), "Cactus Pressure Plate");
        add(ModBlocks.CACTUS_DOOR.get(), "Cactus Door");
        add(ModBlocks.CACTUS_TRAPDOOR.get(), "Cactus Trapdoor");
        add(ModBlocks.CACTUS_SIGN.get(), "Cactus Sign");
        add("block.floraexpansion.cactus_wall_sign", "Cactus Wall Sign");
        add(ModBlocks.CACTUS_HANGING_SIGN.get(), "Cactus Hanging Sign");
        add("block.floraexpansion.cactus_wall_hanging_sign", "Cactus Wall Hanging Sign");
        add(ModBlocks.DESERT_MOSS.get(), "Desert Moss");
        add(ModBlocks.CACTUS_CLUSTER.get(), "Cactus Cluster");
        add(ModBlocks.OPUNTIA_CACTUS.get(), "Opuntia Cactus");

        add("item.floraexpansion.pine_litter", "Pine Litter");
        add("item.floraexpansion.twig_ladder", "Twig Ladder");
        add("item.floraexpansion.crate", "Crate");
        add("item.floraexpansion.strawberry_cake", "Strawberry Cake");
        add("item.floraexpansion.large_blueberry_bush", "Large Blueberry Bush");
        add("item.floraexpansion.linen_carpet", "Linen Carpet");
        add("item.floraexpansion.linen_block", "Linen Block");
        add("item.floraexpansion.pebble_patch", "Pebble Patch");
        add("item.floraexpansion.pebble_block", "Pebble Block");
        add("item.floraexpansion.flax_bale", "Flax Bale");
        add("item.floraexpansion.cherry_pit", "Cherry Pit");
        add("item.floraexpansion.fruiting_cherry_leaves", "Fruiting Cherry Leaves");
        add("item.floraexpansion.apple_core", "Apple Core");
        add("item.floraexpansion.fruiting_oak_leaves", "Fruiting Oak Leaves");
        add("item.floraexpansion.giant_cactus_base", "Giant Cactus Base");
        add("item.floraexpansion.stripped_giant_cactus_base", "Stripped Giant Cactus Base");
        add("item.floraexpansion.giant_cactus_stem", "Giant Cactus Stem");
        add("item.floraexpansion.cactus_thorn", "Cactus Thorn");
        add("item.floraexpansion.giant_cactus_blossom", "Giant Cactus Blossom");
        add("item.floraexpansion.giant_cactus_wood", "Giant Cactus Wood");
        add("item.floraexpansion.stripped_giant_cactus_wood", "Stripped Giant Cactus Wood");
        add("item.floraexpansion.cactus_planks", "Cactus Planks");
        add("item.floraexpansion.cactus_mosaic", "Cactus Mosaic");
        add("item.floraexpansion.cactus_stairs", "Cactus Stairs");
        add("item.floraexpansion.cactus_slab", "Cactus Slab");
        add("item.floraexpansion.cactus_fence", "Cactus Fence");
        add("item.floraexpansion.cactus_fence_gate", "Cactus Fence Gate");
        add("item.floraexpansion.cactus_button", "Cactus Button");
        add("item.floraexpansion.cactus_pressure_plate", "Cactus Pressure Plate");
        add("item.floraexpansion.cactus_door", "Cactus Door");
        add("item.floraexpansion.cactus_trapdoor", "Cactus Trapdoor");
        add("item.floraexpansion.desert_moss", "Desert Moss");
        add("item.floraexpansion.cactus_cluster", "Cactus Cluster");
        add(ModItems.PINE_CONE.get(), "Pine Cone");
        add(ModItems.PINE_NUTS.get(), "Pine Nuts");
        add(ModItems.TOASTED_PINE_NUTS.get(), "Toasted Pine Nuts");
        add(ModItems.TWIG.get(), "Twig");
        add(ModItems.FOREST_SNACK.get(), "Forest Snack");
        add(ModItems.FLAX_SEED.get(), "Flax Seed");
        add(ModItems.FLAX_FIBER.get(), "Flax Fiber");
        add(ModItems.FLAX_FLOWER.get(), "Flax Flower");
        add(ModItems.LINEN_THREAD.get(), "Linen Thread");
        add(ModItems.LINEN_CLOTH.get(), "Linen Cloth");
        add(ModItems.BASKET.get(), "Basket");
        add(ModItems.PEBBLES.get(), "Pebbles");
        add(ModItems.BLUEBERRIES.get(), "Blueberries");
        add(ModItems.BLUEBERRY_COOKIE.get(), "Blueberry Cookie");
        add(ModItems.BLUEBERRY_PIE.get(), "Blueberry Pie");
        add(ModItems.BLUEBERRY_PIE_SLICE.get(), "Blueberry Pie Slice");
        add(ModItems.BLUEBERRY_JUICE.get(), "Blueberry Juice");
        add(ModItems.EMPTY_JAR.get(), "Empty Jar");
        add(ModItems.BLUEBERRY_JAM.get(), "Blueberry Jam");
        add(ModItems.STRAWBERRY.get(), "Strawberry");
        add(ModItems.STRAWBERRY_JAM.get(), "Strawberry Jam");
        add(ModItems.WOODEN_BUCKET.get(), "Wooden Bucket");
        add(ModItems.WOODEN_WATER_BUCKET.get(), "Wooden Water Bucket");
        add(ModItems.WOODEN_LAVA_BUCKET.get(), "Wooden Lava Bucket");
        add(ModItems.WOODEN_POWDER_SNOW_BUCKET.get(), "Wooden Powder Snow Bucket");
        add(ModItems.WOODEN_MILK_BUCKET.get(), "Wooden Milk Bucket");
        add(ModItems.COD_WOODEN_BUCKET.get(), "Wooden Bucket of Cod");
        add(ModItems.SALMON_WOODEN_BUCKET.get(), "Wooden Bucket of Salmon");
        add(ModItems.PUFFERFISH_WOODEN_BUCKET.get(), "Wooden Bucket of Pufferfish");
        add(ModItems.TROPICAL_FISH_WOODEN_BUCKET.get(), "Wooden Bucket of Tropical Fish");
        add(ModItems.AXOLOTL_WOODEN_BUCKET.get(), "Wooden Bucket of Axolotl");
        add(ModItems.TADPOLE_WOODEN_BUCKET.get(), "Wooden Bucket of Tadpole");
        add(ModItems.CHERRIES.get(), "Cherries");
        add(ModItems.SWEET_BERRY_MIX.get(), "Sweet Berry Mix");
        add(ModItems.CHERRY_JUICE.get(), "Cherry Juice");
        add(ModItems.APPLE_JUICE.get(), "Apple Juice");
        add(ModItems.CACTUS_SIGN.get(), "Cactus Sign");
        add(ModItems.CACTUS_HANGING_SIGN.get(), "Cactus Hanging Sign");
        add(ModItems.CACTUS_BOAT.get(), "Cactus Boat");
        add(ModItems.CACTUS_CHEST_BOAT.get(), "Cactus Chest Boat");
        add(ModItems.CACTUS_HELMET.get(), "Cactus Helmet");
        add(ModItems.CACTUS_CHESTPLATE.get(), "Cactus Chestplate");
        add(ModItems.CACTUS_LEGGINGS.get(), "Cactus Leggings");
        add(ModItems.CACTUS_BOOTS.get(), "Cactus Boots");
        add(ModItems.CACTUS_SLICE.get(), "Cactus Slice");
        add(ModItems.CACTUS_JUICE.get(), "Cactus Juice");
        add(ModItems.PRICKLY_PEAR.get(), "Prickly Pear");

        add("entity.floraexpansion.cactus_boat", "Cactus Boat");
        add("entity.floraexpansion.cactus_chest_boat", "Cactus Chest Boat");
    }
}

